### ISSUE TITLE
Use a Darker-but-Still-Light Style for the Search Promotions and Ensure Alignment

### ISSUE THREAD

**Issue by Sporkyy** [merceruniversity/google-cse-customization#7]
See #1 

- [ ] Get accessible colors from @maconmatt

**Comment by Sporkyy** [comment]
The example foreground and background do not have sufficient contrast

[Ratio: 4.37](https://contrastchecker.com/?c=676767&b=E2E2E2)

Using the #676767 grey doesn't leave much headroom for using it on a dark background. Even a very-light dark background. That's one of the reasons I went with a very dark background and very-light grey for the promotions.

**Comment by maconmatt** [comment]
Let's try using our "black" for the text in the promoted results. http://branding.mercer.edu/color/

**Comment by Sporkyy** [comment]
@maconmatt Did you just make up that grey used for the promotions background?

I don't see it listed in the official branding colors. (Neither on the page to which you linked nor the Sketch file.)

Is there another color scale somewhere?
